export const stackOptions = [
    { value: "Javascript", label: "Javascript" },
    { value: "React", label: "React" },
    { value: "Typescript", label: "Typescript" },
    { value: "Storybook", label: "Storybook" },
    { value: "Remix", label: "Remix" },
    { value: "Vercel", label: "Vercel" },
    { value: "React Query", label: "React Query" },
    { value: "SWR", label: "SWR" },
    { value: "MUI", label: "MUI" }, 
    { value: "Chrome MV3", label: "Chrome MV3" },
    { value: "Mantine", label: "Mantine" },
    { value: "Tailwind", label: "Tailwind" },
    { value: "Node", label: "Node" },
    { value: "Express", label: "Express" },
    { value: "MongoDB", label: "MongoDB" },
    { value: "Mongoose", label: "Mongoose" },
    { value: "MongoDB Atlas", label: "MongoDB Atlas" },
    { value: "Supabase", label: "Supabase" },
    { value: "Docker", label: "Docker" },
    { value: "Azure", label: "Azure" },
    { value: "React Native", label: "React Native" },
    { value: "Electron", label: "Electron" },
    { value: "Next", label: "Next" },
    { value: "Gatsby", label: "Gatsby" },
    { value: "GraphQL", label: "GraphQL" },
    { value: "PHP", label: "PHP" },
    { value: "Laravel", label: "Laravel" },
    { value: "MySQL", label: "MySQL" },
    { value: "PostgreSQL", label: "PostgreSQL" },
    { value: "Redis", label: "Redis" },
    { value: "RabbitMQ", label: "RabbitMQ" },
    { value: "Kafka", label: "Kafka" },
    
  ];
  